#!/bin/bash
set -e

volume() {
    VOL=$(pamixer --get-volume)
}

mute() {
    if [[ $(pamixer --get-mute) = "true" ]] ; then
        MUTE="mute"
    fi
}

print_volume() {
    if [[ -z "$MUTE" ]] ; then
        printf "%3s%%\n" $VOL
    else
        echo "mute"
    fi
}

STEP=5
case $BLOCK_BUTTON in
  3) pamixer -t ;;  # right click, mute/unmute
  4) pamixer -u -i ${STEP} ;; # scroll up, increase
  5) pamixer -u -d ${STEP} ;; # scroll down, decrease
esac

volume
mute
print_volume

