#!/usr/bin/sh
INTERFACE="enp3s0f0"
STATUS=$(networkctl status $INTERFACE | grep "State:" | awk '{print $2}')
if [ "$STATUS" == "routable" ]; then
    ADDR=$(ip addr show dev $INTERFACE | grep "inet\>" | awk '{print $2}')
    echo -e "${ADDR}\n\n#8CFF2D"
else
    echo -e "N/A\n\n#FE2E2E"
fi

